- name: Install and configure the system
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Include core tasks
      include_tasks: tasks/core.yml

    - name: Include Fonts setup
      include_tasks: tasks/fonts.yml

    - name: Include Fish shell setup
      include_tasks: tasks/shells/fish.yml

